### ISSUE TITLE
what size belts do you use for the intake?

### ISSUE THREAD

**Issue by SumnerHull** [CranberryAlarm/CA24_RobotCode#7]

**Comment by dracco1993** [comment]
From Reis in our CD thread:
> We used 9mm wide HTD 5mm belts everywhere on the intake. I like to use [WCP belt calculator 7](https://wcproducts.com/pages/calculator-belt) for all my center to center distance calculations.
> I just found some geometry that worked in CAD, plugged the number in the calculator and found the nearest length belt. As for pulleys, we used 24T HTD 5mm pulleys everywhere, using the 15mm wide ones where needed.

You can find the full thread here:
https://www.chiefdelphi.com/t/ri3d-cranberry-alarm-2024-now-with-more-fun/447177/70?u=dracco
